# Generated by Django 3.2.13 on 2022-06-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('VIP', 'VIP')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
