# Generated by Django 3.2.13 on 2022-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
