# Generated by Django 3.2.13 on 2022-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
        ('actor', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='uploads/movies/%Y/%m')),
                ('actors', models.ManyToManyField(related_name='movies', to='actor.Actor')),
                ('directors', models.ManyToManyField(related_name='movies', to='director.Director')),
                ('genres', models.ManyToManyField(related_name='movies', to='genre.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
