# Generated by Django 3.2.13 on 2022-06-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
