# Generated by Django 3.2.13 on 2022-06-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.TextField(default='https://www.youtube.com/embed/SNkwT1DfmVU'),
        ),
    ]
