# Generated by Django 3.2.13 on 2022-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20220618_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
    ]
