# Generated by Django 3.2.15 on 2022-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_is_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
