# Generated by Django 3.2.13 on 2022-06-11 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('row', models.CharField(max_length=1)),
                ('column', models.CharField(max_length=2)),
                ('type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('VIP', 'VIP')], max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='room.room')),
            ],
            options={
                'unique_together': {('row', 'column', 'room')},
            },
        ),
    ]
