# Generated by Django 3.2.13 on 2022-06-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('room', '0001_initial'),
        ('show_date', '0001_initial'),
        ('show_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_movies', to='movie.movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_movies', to='room.room')),
                ('show_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_movies', to='show_date.showdate')),
                ('show_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_movies', to='show_time.showtime')),
            ],
            options={
                'db_table': 'theater_schedule_movie',
                'unique_together': {('room', 'show_date', 'show_time')},
            },
        ),
    ]
